version: '3.3'
services:
  #PHP
  php:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    container_name: sea-protection-association-php
    restart: always
    env_file:
      - ./resources/.env
    volumes:
      - "./resources:/app:cached"

  #NGNIX
  ngnix:
    image: nginx:1.22-alpine
    container_name: sea-protection-association-nginx
    restart: always
    ports:
      - "8080:80"
    env_file:
      - ./resources/.env
    volumes:
      - "./dockerfiles/nginx/project.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./resources:/app:cached"
    depends_on:
      - php
    networks:
      - default

  # Database
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: sea_protection_association_db_container
    environment:
      MYSQL_ROOT_PASSWORD: myPassword
      MYSQL_DATABASE: sea-protection-association
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myPassword
      TZ: 'Europe/Paris'
    ports:
      - "3306:3306"

networks:
  default:
    external:
      name: apis