App\DTO\Event\CreateEventDTO:
    properties:
        title:
            - Type: string
            - NotBlank: ~
        address:
            - Type: string
            - NotBlank: ~
        date:
            - DateTime: ~
            - NotBlank: ~

