App\DTO\Service\UpdateServiceDTO:
    properties:
        id:
            - Type: integer
            - NotBlank: ~
        name:
            - Type: string
            - NotBlank: ~
        isActive:
            - Type: boolean
