App\DTO\Contact\ContactDTO:
    properties:
        lastName:
            - Type: string
            - NotBlank: ~
        email:
            - Type: string
            - NotBlank: ~
            - Email: ~
        message:
            - Type: string
            - NotBlank: ~
        phoneNumber:
            - Type: string
            - NotBlank: ~
            - Regex: '/^0[1|2|3|4|5|6|7|9][0-9]{8}$/'
