App\DTO\User\LoginDTO:
    properties:
        email:
            - Type: string
            - NotBlank: ~
            - Email: ~
        password:
            - Type: string
            - NotBlank: ~
