App\DTO\User\UpdatePasswordDTO:
    properties:
        password:
            - Type: string
            - NotBlank: ~
        newPassword:
            - Type: string
            - NotBlank: ~
        newPasswordConfirmation:
            - Type: string
            - NotBlank: ~
